Download all molecules that have been tested against the target of interest - epidermal growth factor receptor (EGFR) kinase.

In [3]:
import math
from pathlib import Path
from zipfile import ZipFile
from tempfile import TemporaryDirectory

import numpy as np
import pandas as pd
from rdkit.Chem import PandasTools
from chembl_webresource_client.new_client import new_client
import tqdm as notebook_tqdm

In [4]:
last_dir = Path(_dh[-1])
print(f"Current working directory: {last_dir}")

Current working directory: /Users/duncanfreeman/dev/bioinfo/notebooks/volkmer

In [5]:
targets_api = new_client.target
compounds_api = new_client.molecule
bioactivities_api = new_client.activity

In [6]:
uniprot_id = "P00533"
# Get target information from ChEMBL but restrict it to specified values only
targets = targets_api.get(target_components__accession=uniprot_id).only(
    "target_chembl_id", "organism", "pref_name", "target_type"
)
print(f'The type of the targets is "{type(targets)}"')
targets = pd.DataFrame.from_records(targets)
targets

The type of the targets is "<class 'chembl_webresource_client.query_set.QuerySet'>"

,organism,pref_name,target_chembl_id,target_type
0,Homo sapiens,Epidermal growth factor receptor,CHEMBL203,SINGLE PROTEIN
1,Homo sapiens,Epidermal growth factor receptor,CHEMBL203,SINGLE PROTEIN
2,Homo sapiens,Epidermal growth factor receptor and ErbB2 (HE...,CHEMBL2111431,PROTEIN FAMILY
3,Homo sapiens,Epidermal growth factor receptor,CHEMBL2363049,PROTEIN FAMILY
4,Homo sapiens,MER intracellular domain/EGFR extracellular do...,CHEMBL3137284,CHIMERIC PROTEIN
5,Homo sapiens,Protein cereblon/Epidermal growth factor receptor,CHEMBL4523680,PROTEIN-PROTEIN INTERACTION
6,Homo sapiens,EGFR/PPP1CA,CHEMBL4523747,PROTEIN-PROTEIN INTERACTION
7,Homo sapiens,von Hippel-Lindau disease tumor suppressor/Epi...,CHEMBL4523998,PROTEIN-PROTEIN INTERACTION
8,Homo sapiens,Baculoviral IAP repeat-containing protein 2/Ep...,CHEMBL4802031,PROTEIN-PROTEIN INTERACTION
9,Homo sapiens,CCN2-EGFR,CHEMBL5465557,PROTEIN-PROTEIN INTERACTION
10,Homo sapiens,Microtubule-associated protein 1 light chain 3...,CHEMBL6066839,PROTEIN-PROTEIN INTERACTION
11,Homo sapiens,Glucose-induced degradation protein 4 homolog/...,CHEMBL6066845,PROTEIN-PROTEIN INTERACTION
12,Homo sapiens,E3 ubiquitin-protein ligase Mdm2/Epidermal gro...,CHEMBL6193792,PROTEIN-PROTEIN INTERACTION
13,Homo sapiens,UBR/Epidermal growth factor receptor,CHEMBL6193830,PROTEIN-PROTEIN INTERACTION
14,Homo sapiens,Protein zyg-11 homolog B/Protein zer-1 homolog...,CHEMBL6193837,PROTEIN-PROTEIN INTERACTION
15,Mus musculus,Protein cereblon/Epidermal growth factor receptor,CHEMBL6193841,PROTEIN-PROTEIN INTERACTION
16,Homo sapiens,E3 ubiquitin-protein ligase RNF149/Epidermal g...,CHEMBL6195769,PROTEIN-PROTEIN INTERACTION

In [7]:
target = targets.iloc[0]
target

organism                                Homo sapiens
pref_name           Epidermal growth factor receptor
target_chembl_id                           CHEMBL203
target_type                           SINGLE PROTEIN
Name: 0, dtype: str

In [8]:
chembl_id = target.target_chembl_id
print(f"The target ChEMBL ID is {chembl_id}")
# NBVAL_CHECK_OUTPUT

The target ChEMBL ID is CHEMBL203

In [9]:
bioactivities = bioactivities_api.filter(
    target_chembl_id=chembl_id, type="IC50", relation="=", assay_type="B"
).only(
    "activity_id",
    "assay_chembl_id",
    "assay_description",
    "assay_type",
    "molecule_chembl_id",
    "type",
    "standard_units",
    "relation",
    "standard_value",
    "target_chembl_id",
    "target_organism",
)

print(f"Length and type of bioactivities object: {len(bioactivities)}, {type(bioactivities)}")

Length and type of bioactivities object: 17686, <class 'chembl_webresource_client.query_set.QuerySet'>

In [10]:
print(f"Length and type of first element: {len(bioactivities[0])}, {type(bioactivities[0])}")
bioactivities[0]

Length and type of first element: 13, <class 'dict'>

{'activity_id': 32260,
 'assay_chembl_id': 'CHEMBL674637',
 'assay_description': 'Inhibitory activity towards tyrosine phosphorylation for the epidermal growth factor-receptor kinase',
 'assay_type': 'B',
 'molecule_chembl_id': 'CHEMBL68920',
 'relation': '=',
 'standard_units': 'nM',
 'standard_value': '41.0',
 'target_chembl_id': 'CHEMBL203',
 'target_organism': 'Homo sapiens',
 'type': 'IC50',
 'units': 'uM',
 'value': '0.041'}

In [11]:
bioactivities_df = pd.DataFrame.from_dict(bioactivities)
print(f"DataFrame shape: {bioactivities_df.shape}")
bioactivities_df.head()

DataFrame shape: (17686, 13)

,activity_id,assay_chembl_id,assay_description,assay_type,molecule_chembl_id,relation,standard_units,standard_value,target_chembl_id,target_organism,type,units,value
0,32260,CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,CHEMBL68920,=,nM,41.0,CHEMBL203,Homo sapiens,IC50,uM,0.041
1,32267,CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,CHEMBL69960,=,nM,170.0,CHEMBL203,Homo sapiens,IC50,uM,0.17
2,32680,CHEMBL677833,In vitro inhibition of Epidermal growth factor...,B,CHEMBL137635,=,nM,9300.0,CHEMBL203,Homo sapiens,IC50,uM,9.3
3,32770,CHEMBL674643,Inhibitory concentration of EGF dependent auto...,B,CHEMBL306988,=,nM,500000.0,CHEMBL203,Homo sapiens,IC50,uM,500.0
4,32772,CHEMBL674643,Inhibitory concentration of EGF dependent auto...,B,CHEMBL66879,=,nM,3000000.0,CHEMBL203,Homo sapiens,IC50,uM,3000.0

The first two rows describe the same bioactivity entry; we will remove such artifacts later during the deduplication step. Note also that we have columns for standard_units/units and standard_values/values; in the following, we will use the standardized columns (standardization by ChEMBL), and thus, we drop the other two columns.

If we used the units and values columns, we would need to convert all values with many different units to nM:

In [12]:
bioactivities_df["units"].unique()

<StringArray>
[         'uM',          'nM',          'pM',           'M',     '10'3 uM',
  '10'1 ug/ml',     'ug ml-1', '10'-1microM',     '10'1 uM', '10'-1 ug/ml',
 '10'-2 ug/ml',     '10'2 uM', '10'-3 ug/ml', '10'-2microM',         '/uM',
   '10'-6g/ml',          'mM',      'umol/L',      'nmol/L',     '10'-10M',
      '10'-7M',        'nmol',      '10^-8M',     '10^3 uM']
Length: 24, dtype: str

In [13]:
bioactivities_df["value"].unique()

<StringArray>
[ '0.041',   '0.17',    '9.3',  '500.0', '3000.0',   '96.0',   '5.31',
  '264.0',  '0.125',   '35.0',
 ...
 '158.57', '307.11',  '291.7',   '48.4',   '75.8',  '117.7',  '894.7',
  '130.1',   '4.81',  '13.08']
Length: 4137, dtype: str

In [14]:
bioactivities_df.drop(["units", "value"], axis=1, inplace=True)
bioactivities_df.head()

,activity_id,assay_chembl_id,assay_description,assay_type,molecule_chembl_id,relation,standard_units,standard_value,target_chembl_id,target_organism,type
0,32260,CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,CHEMBL68920,=,nM,41.0,CHEMBL203,Homo sapiens,IC50
1,32267,CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,CHEMBL69960,=,nM,170.0,CHEMBL203,Homo sapiens,IC50
2,32680,CHEMBL677833,In vitro inhibition of Epidermal growth factor...,B,CHEMBL137635,=,nM,9300.0,CHEMBL203,Homo sapiens,IC50
3,32770,CHEMBL674643,Inhibitory concentration of EGF dependent auto...,B,CHEMBL306988,=,nM,500000.0,CHEMBL203,Homo sapiens,IC50
4,32772,CHEMBL674643,Inhibitory concentration of EGF dependent auto...,B,CHEMBL66879,=,nM,3000000.0,CHEMBL203,Homo sapiens,IC50

In [15]:
bioactivities_df = bioactivities_df.astype({"standard_value": "float64"})
bioactivities_df.dtypes

activity_id             int64
assay_chembl_id           str
assay_description         str
assay_type                str
molecule_chembl_id        str
relation                  str
standard_units            str
standard_value        float64
target_chembl_id          str
target_organism           str
type                      str
dtype: object

In [16]:
bioactivities_df.dropna(axis=0, how="any", inplace=True)
print(f"DataFrame shape: {bioactivities_df.shape}")
print(f"Units in downloaded data: {bioactivities_df['standard_units'].unique()}")
print(f"Number of non-nM entries: {bioactivities_df[bioactivities_df['standard_units'] != 'nM'].shape[0]}")
print(f"DataFrame shape: {bioactivities_df.shape}")

DataFrame shape: (17685, 11)
Units in downloaded data: <StringArray>
['nM', 'ug.mL-1', '/uM', '10^3 uM']
Length: 4, dtype: str
Number of non-nM entries: 73
DataFrame shape: (17685, 11)

In [17]:
bioactivities_df = bioactivities_df[bioactivities_df["standard_units"] == "nM"]
print(f"Units after filtering: {bioactivities_df['standard_units'].unique()}")

Units after filtering: <StringArray>
['nM']
Length: 1, dtype: str

In [18]:
bioactivities_df.drop_duplicates("molecule_chembl_id", keep="first", inplace=True)
print(f"DataFrame shape: {bioactivities_df.shape}")

DataFrame shape: (10220, 11)

In [19]:
bioactivities_df.reset_index(drop=True, inplace=True)
bioactivities_df.rename(
    columns={"standard_value": "IC50", "standard_units": "units"}, inplace=True
)
bioactivities_df.head(2)

,activity_id,assay_chembl_id,assay_description,assay_type,molecule_chembl_id,relation,units,IC50,target_chembl_id,target_organism,type
0,32260,CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,CHEMBL68920,=,nM,41.0,CHEMBL203,Homo sapiens,IC50
1,32267,CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,CHEMBL69960,=,nM,170.0,CHEMBL203,Homo sapiens,IC50

In [20]:
print(f"Number of unique molecules: {bioactivities_df['molecule_chembl_id'].nunique()}")
print(f"Number of unique assays: {bioactivities_df['assay_chembl_id'].nunique()}")
print(f"Number of unique activities: {bioactivities_df['activity_id'].nunique()}")
print(f"Number of unique targets: {bioactivities_df['target_chembl_id'].nunique()}")

Number of unique molecules: 10220
Number of unique assays: 1107
Number of unique activities: 10220
Number of unique targets: 1

Dataframe contains all molecules tested against EGFR.
Retrieve the molecular structures of the molecules that are linked to respective bioactivity ChEMBL IDs.

Fetch compound data from ChEMBL¶
Let’s have a look at the compounds from ChEMBL which we have defined bioactivity data for: 
- Fetch compound ChEMBL IDs and structures for the compounds linked to our filtered bioactivity data.

In [21]:
compounds_provider = compounds_api.filter(
    molecule_chembl_id__in=list(bioactivities_df["molecule_chembl_id"])
).only("molecule_chembl_id", "molecule_structures")